apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
  labels:
    app: teastore
    run: teastore-registry
spec:
  selector:
      matchLabels:
        app: teastore
        run: teastore-registry
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-registry
    spec:
      containers:
      - name: teastore-registry
        image: shinhyungyang/teastore-registry:livedemo-k3s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  labels:
    app: teastore
    run: teastore-registry
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
